#!/bin/bash
# Passes content of Current Workdir to try and generate pdf
# Requires Groff, dmenu and Awk to be installed on system
inputFile=$(ls | dmenu)
pandoc $inputFile -o out.pdf && echo ">>> Done converting $inputFile to pdf"
